[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --no-input",
  "POSTGRES_LOCALLY=true python manage.py migrate --no-input"
]

[start]
cmd = "python manage.py migrate --no-input && daphne -b 0.0.0.0 -p $PORT schoolcamp.asgi:application --verbosity 2"
