# Generated by Django 5.0.14 on 2026-03-09 15:26

import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English Language'), ('french', 'French Language'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('computer_science', 'Computer Science'), ('philosophy', 'Philosophy'), ('literature', 'Literature'), ('other', 'Other')], max_length=30)),
                ('level', models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('form5', 'Form 5'), ('lower6', 'Lower Sixth'), ('upper6', 'Upper Sixth'), ('university', 'University'), ('all', 'All Levels')], default='all', max_length=20)),
                ('file', models.FileField(upload_to=materials.models.material_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('image', 'Image'), ('zip', 'ZIP Archive'), ('other', 'Other')], default='pdf', max_length=10)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in XAF. Set 0 for free.')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='material_previews/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='materials.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'material')},
            },
        ),
    ]
