# Generated by Django 5.0.14 on 2026-03-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
    ]
