# Generated by Django 5.2.1 on 2026-05-10 06:59

import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(upload_to=materials.models.material_upload_path)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('image', 'Image'), ('zip', 'ZIP Archive'), ('other', 'Other')], default='pdf', max_length=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solutio_paper', to='materials.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
