# Generated by Django 5.2.1 on 2026-05-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_uploader_solutions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solutions',
        ),
    ]
