# Generated by Django 5.2.1 on 2026-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_replylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
