# Generated by Django 5.2.1 on 2026-08-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_question_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
    ]
