# Generated by Django 5.2.1 on 2026-08-09 01:09

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_question_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.question_image_upload_path),
        ),
    ]
