# Generated by Django 5.2.1 on 2026-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/group_files/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
