# Generated by Django 5.2.1 on 2026-06-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_videocall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
