# Generated by Django 5.2.1 on 2026-07-17 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('total_materials_uploaded', models.PositiveIntegerField(default=0)),
                ('total_materials_downloaded', models.PositiveIntegerField(default=0)),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0)),
                ('total_quizzes_passed', models.PositiveIntegerField(default=0)),
                ('total_questions_asked', models.PositiveIntegerField(default=0)),
                ('total_replies_posted', models.PositiveIntegerField(default=0)),
                ('total_answers_accepted', models.PositiveIntegerField(default=0)),
                ('total_groups_created', models.PositiveIntegerField(default=0)),
                ('total_groups_joined', models.PositiveIntegerField(default=0)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('weekly_rank', models.PositiveIntegerField(default=0)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('global_rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('has_freeze', models.BooleanField(default=False)),
                ('freeze_expires_at', models.DateTimeField(blank=True, null=True)),
                ('freezes_used', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('material_upload', 'Material Upload'), ('material_download', 'Material Download'), ('material_view', 'Material View'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_pass', 'Quiz Passed'), ('question_post', 'Question Posted'), ('question_reply', 'Reply Posted'), ('question_like', 'Question Liked'), ('reply_like', 'Reply Liked'), ('answer_accepted', 'Answer Accepted'), ('timetable_create', 'Timetable Created'), ('timetable_update', 'Timetable Updated'), ('course_add', 'Course Added'), ('group_create', 'Study Group Created'), ('group_join', 'Study Group Joined'), ('group_post', 'Group Post'), ('login', 'Login'), ('xp_earned', 'XP Earned')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='dashboard_u_user_id_742927_idx'), models.Index(fields=['user', 'activity_type'], name='dashboard_u_user_id_5150cc_idx'), models.Index(fields=['created_at'], name='dashboard_u_created_8f7e1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('activities_count', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Leaderboard Entry',
                'verbose_name_plural': 'Weekly Leaderboard Entries',
                'ordering': ['-xp_earned', 'user__username'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
