# Generated by Django 5.2.1 on 2026-06-07 14:25

import GCE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='solution',
            field=models.FileField(upload_to=GCE.models.solution_upload_path),
        ),
    ]
