# Generated by Django 5.0.14 on 2026-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GROUPS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroups',
            old_name='Creator_of',
            new_name='Creator',
        ),
        migrations.AlterField(
            model_name='studygroups',
            name='privacy',
            field=models.CharField(choices=[('PUPLIC', 'public'), ('PRIVATE', 'PRIVATE')], default='Public', max_length=10),
        ),
    ]
