# Generated by Django 5.0.14 on 2026-03-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GROUPS', '0002_rename_creator_of_studygroups_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroups',
            old_name='Name',
            new_name='group_Name',
        ),
    ]
