# Generated by Django 5.2.1 on 2026-07-08

from django.conf import settings
from django.db import migrations
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    """
    migrate data from old table structure to new table structure
    """
    db_alias = schema_editor.connection.alias

    # Rename the old table to preserve data
    schema_editor.execute(
        "ALTER TABLE notifications_notification RENAME TO notifications_notification_old"
    )

    # Create the new table with correct schema
    # Note: We don't add foreign key constraints here because SQLite doesn't support
    # adding them via ALTER TABLE easily, and we want to avoid complications.
    # The constraints will be added Django's way when the migration runs.
    schema_editor.execute("""
        CREATE TABLE notifications_notification (
            "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            "verb" varchar(255) NOT NULL,
            "description" text NULL,
            "notification_type" varchar(30) NOT NULL,
            "target_object_id" integer NULL,
            "is_read" bool NOT NULL,
            "created_at" datetime NOT NULL,
            "actor_id" bigint NULL,
            "recipient_id" bigint NOT NULL,
            "target_content_type_id" integer NULL
        )
    """)

    # Copy and transform data from old table to new table
    # Old table columns: id, notif_type, title, message, url, is_read, created_at, recipient_id, sender_id
    # New table columns: id, verb, description, notification_type, target_object_id, is_read, created_at, actor_id, recipient_id, target_content_type_id
    #
    # Mapping:
    # id -> id
    # notif_type -> notification_type
    # title -> verb
    # message -> description
    # url -> (ignored)
    # is_read -> is_read
    # created_at -> created_at
    # recipient_id -> recipient_id
    # sender_id -> actor_id
    # target_object_id -> NULL
    # target_content_type_id -> NULL

    schema_editor.execute("""
        INSERT INTO notifications_notification
        (id, verb, description, notification_type, target_object_id, is_read, created_at, actor_id, recipient_id, target_content_type_id)
        SELECT
            id,
            title,
            message,
            notif_type,
            NULL,
            is_read,
            created_at,
            sender_id,
            recipient_id,
            NULL
        FROM notifications_notification_old
    """)


def reverse_func(apps, schema_editor):
    """
    reverse the migration - convert new table back to old structure
    """
    db_alias = schema_editor.connection.alias

    # Rename current table to temporary name
    schema_editor.execute(
        "ALTER TABLE notifications_notification RENAME TO notifications_notification_new"
    )

    # Recreate old table structure
    schema_editor.execute("""
        CREATE TABLE notifications_notification (
            "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            "notif_type" varchar(15) NOT NULL,
            "title" varchar(100) NOT NULL,
            "message" varchar(255) NOT NULL,
            "url" varchar(255) NOT NULL,
            "is_read" bool NOT NULL,
            "created_at" datetime NOT NULL,
            "recipient_id" bigint NOT NULL,
            "sender_id" bigint NULL
        )
    """)

    # Copy data back (best effort)
    schema_editor.execute("""
        INSERT INTO notifications_notification
        (id, notif_type, title, message, url, is_read, created_at, recipient_id, sender_id)
        SELECT
            id,
            notification_type,
            COALESCE(verb, 'Unknown'),
            COALESCE(description, ''),
            '',
            is_read,
            created_at,
            recipient_id,
            actor_id
        FROM notifications_notification_new
    """)

    # Drop the new table
    schema_editor.execute("DROP TABLE notifications_notification_new")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]